import AppKit
import PDFKit

@MainActor
enum PDFExporter {
    static func export(store: MetricStore, targets: [PingTarget]) -> PDFDocument {
        let pageSize = CGRect(x: 0, y: 0, width: 595, height: 842)  // A4
        let document = PDFDocument()
        let data = renderPage(store: store, targets: targets, pageSize: pageSize)

        if let page = PDFPage(image: NSImage(data: data) ?? NSImage()) {
            document.insert(page, at: 0)
        }
        return document
    }

    // MARK: - Render to bitmap

    private static func renderPage(store: MetricStore, targets: [PingTarget], pageSize: CGRect) -> Data {
        let scale: CGFloat = 2  // Retina
        let bitmapSize = NSSize(width: pageSize.width * scale, height: pageSize.height * scale)

        let rep = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: Int(bitmapSize.width),
            pixelsHigh: Int(bitmapSize.height),
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .calibratedRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        )!

        NSGraphicsContext.saveGraphicsState()
        let ctx = NSGraphicsContext(bitmapImageRep: rep)!
        ctx.cgContext.scaleBy(x: scale, y: scale)
        NSGraphicsContext.current = ctx

        drawContent(store: store, targets: targets, in: pageSize)

        NSGraphicsContext.restoreGraphicsState()
        return rep.representation(using: .png, properties: [:]) ?? Data()
    }

    private static func drawContent(store: MetricStore, targets: [PingTarget], in rect: CGRect) {
        // Background
        NSColor.white.setFill()
        NSBezierPath.fill(rect)

        let margin: CGFloat = 40
        var y = rect.height - margin

        // Title
        y = drawText("Me Or Them — Network Report",
                     at: NSPoint(x: margin, y: y - 24),
                     font: .boldSystemFont(ofSize: 18),
                     color: .black)
        y -= 4
        y = drawText(ISO8601DateFormatter().string(from: Date()),
                     at: NSPoint(x: margin, y: y - 14),
                     font: .systemFont(ofSize: 10),
                     color: .secondaryLabelColor)
        y -= 20

        // Separator
        drawLine(from: NSPoint(x: margin, y: y), to: NSPoint(x: rect.width - margin, y: y))
        y -= 20

        // Ping section
        y = drawText("PING TARGETS",
                     at: NSPoint(x: margin, y: y - 14),
                     font: .boldSystemFont(ofSize: 12),
                     color: .secondaryLabelColor)
        y -= 8

        for target in targets {
            guard let r = store.latestPing[target.id] else { continue }
            let rttStr  = r.rtt.map { String(format: "%.1f ms", $0) } ?? "timeout"
            let lossStr = String(format: "%.1f%% loss", r.lossPercent)
            let jitStr  = r.jitter.map { String(format: "±%.1f ms", $0) } ?? ""

            let dot = NSBezierPath(ovalIn: NSRect(x: margin, y: y - 10, width: 10, height: 10))
            let status = MetricStatus.forPingResult(r, thresholds: .default)
            status.color.setFill()
            dot.fill()

            y = drawText("\(target.label) (\(target.host))  \(rttStr)  \(lossStr)  \(jitStr)",
                         at: NSPoint(x: margin + 16, y: y - 13),
                         font: .monospacedSystemFont(ofSize: 10, weight: .regular),
                         color: .labelColor)
            y -= 4
        }

        y -= 12
        drawLine(from: NSPoint(x: margin, y: y), to: NSPoint(x: rect.width - margin, y: y))
        y -= 20

        // WiFi section
        if let w = store.latestWifi {
            y = drawText("WI-FI",
                         at: NSPoint(x: margin, y: y - 14),
                         font: .boldSystemFont(ofSize: 12),
                         color: .secondaryLabelColor)
            y -= 8
            let lines = [
                "SSID: \(w.ssid)  |  BSSID: \(w.bssid)",
                "RSSI: \(w.rssi) dBm (\(w.rssiQuality))  |  SNR: \(w.snr) dB",
                "Channel: \(w.channelNumber) (\(String(format: "%.1f", w.channelBandGHz)) GHz)  |  TX Rate: \(String(format: "%.0f Mbps", w.txRateMbps))",
            ]
            for line in lines {
                y = drawText(line,
                             at: NSPoint(x: margin, y: y - 13),
                             font: .monospacedSystemFont(ofSize: 10, weight: .regular),
                             color: .labelColor)
                y -= 4
            }
        }

        // Footer
        drawText("Generated by Me Or Them",
                 at: NSPoint(x: margin, y: 20),
                 font: .systemFont(ofSize: 9),
                 color: .tertiaryLabelColor)
    }

    @discardableResult
    private static func drawText(_ text: String, at point: NSPoint,
                                  font: NSFont, color: NSColor) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
        let str = NSAttributedString(string: text, attributes: attrs)
        str.draw(at: point)
        return point.y
    }

    private static func drawLine(from: NSPoint, to: NSPoint) {
        let path = NSBezierPath()
        path.move(to: from)
        path.line(to: to)
        path.lineWidth = 0.5
        NSColor.separatorColor.setStroke()
        path.stroke()
    }
}
